Join tables
silviatofana/vetclinic-database pull request #4
Opened 2022-08-10 20:35 UTC by silviatofana

In this PR I did the following:
Create a table named vets
Create a join table called specializations and visits
Insert the data for vets, specializations, and visits
Write queries
Attached here is the screenshot :

![image](https://user-images.githubusercontent.com/100236377/184014285-074eec3f-38fe-4638-b47d-d33876402c67.png)

![image](https://user-images.githubusercontent.com/100236377/184014325-885ab5f2-a150-4cbb-8f12-cf5278902542.png)

![image](https://user-images.githubusercontent.com/100236377/184014363-6a586dda-10d4-4c45-b29b-a5036ac7fe5a.png)

![image](https://user-images.githubusercontent.com/100236377/184014412-5eddb02d-4409-48ac-bc8c-d51a204c50de.png)

![image](https://user-images.githubusercontent.com/100236377/184014467-d2e0b4c2-e598-4273-ab6a-2eaa8457b957.png)

![image](https://user-images.githubusercontent.com/100236377/184014527-62dd1096-d1e3-4f4f-a0b9-d9330d5c2b55.png)

![image](https://user-images.githubusercontent.com/100236377/184014659-88f7b440-52d1-429a-9f5c-cff7f5426b12.png)

![image](https://user-images.githubusercontent.com/100236377/184014717-5ce25807-5e93-445e-9ce2-5174a4cfa2fb.png)

![image](https://user-images.githubusercontent.com/100236377/184014760-29e46026-4db2-406c-89f2-c7669e6b352f.png)

![image](https://user-images.githubusercontent.com/100236377/184014794-6620a3d4-5a01-4fa7-bc38-a44bd2a1520c.png)

![image](https://user-images.githubusercontent.com/100236377/184014827-11593220-1189-451f-bd1e-5fd4e74cae2e.png)

![image](https://user-images.githubusercontent.com/100236377/184014849-163a79fa-29e5-4bc3-8716-37a90d9ec940.png)

![image](https://user-images.githubusercontent.com/100236377/184014894-f929c4b8-2312-429b-a41f-c7bfb63822bb.png)

2022-08-10 21:18 UTC, BenMukebo requested changes
### Hi @silviatofana,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-10 21:18 UTC, BenMukebo commented on schema.sql
> +  CONSTRAINT fk_visits_vet FOREIGN KEY(vets_id) REFERENCES vets(id)
- [OPTIONAL ] Kindly, According to the naming convention, the foreign key must always be a singular name example:
```
  animal_id INT,
  vet_id INT,
```

2022-08-10 21:18 UTC, BenMukebo commented on data.sql
> +
- [ ] You were instructed to add the following data for `vets` table 👇🏻  but the name is different, 

  - Vet William Tatcher is 45 years old and graduated Apr 23rd, 2000.
  - Vet Maisy Smith is 26 years old and graduated Jan 17th, 2019.
  - Vet Stephanie Mendez is 64 years old and graduated May 4th, 1981.
  - Vet Jack Harkness is 38 years old and graduated Jun 8th, 2008.
- [ ] Kindly remove the `Vet` in front of your names, your code should be like this:

```sql
   INSERT INTO vets (name, age, date_of_graduation)
   VALUES ('William Tatcher', 45, '2000-04-23');

   INSERT INTO vets (name, age, date_of_graduation)
   VALUES ('Maisy Smith', 26, '2019-01-17');

   INSERT INTO vets (name, age, date_of_graduation)
   VALUES ('Stephanie Mendez', 64, '1981-05-04');

   INSERT INTO vets (name, age, date_of_graduation)
   VALUES ('Jack Harknes', 38, '2008-06-08');
```

2022-08-10 21:18 UTC, BenMukebo commented on data.sql
> +
- [ ] Kindly don't forget to modify the 'Vet Stephanie Mendez' and 'Vet Stephanie Mendez' names after removing the `vet`. Your code might look like this:

```sql
 INSERT INTO specializations (species_id, vet_id)
 VALUES ((SELECT id FROM vets WHERE name = 'Stephanie Mendez'), (SELECT id FROM species WHERE name = 'Digimon'));

 INSERT INTO specializations (species_id, vet_id)
 VALUES ((SELECT id FROM vets WHERE name = 'Jack Harkness'), (SELECT id FROM species WHERE name = 'Digimon'));
```

2022-08-11 07:52 UTC, gemmen29 approved these changes
Hi @silviatofana, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-11 07:56 UTC, silviatofana commented
thanks

2022-08-11 07:56 UTC, merged